currency_whole_name_to_code = {
     'Argentine Peso': 'ARS',
    'Bangladesh Taka': 'BDT',
    'Bahraini Dinar': 'BHD',
    'Hongkong Dollar':'HKD',
    'Brazilian Real': 'BRL',
    'Botswana Pula': 'BWP',
    'Belarus Rouble': 'BYN',
    'Chilean Peso': 'CLP',
    'Chinese Yuan - Offshore': 'CNH',
    'Chinese Yuan': 'CNY',
    'Colombian Peso': 'COP',
    'Czech Koruna': 'CZK',
    'Hong Kong Dollar': 'HKD',
    'Hungarian Forint': 'HUF',
    'Iceland Krona': 'ISK',
    'Kenya Shilling': 'KES',
    'Korean Won': 'KRW',
    'Kuwaiti Dinar': 'KWD',
    'Kazakhstan Tenge': 'KZT',
    'Lebanon Pound': 'LBP',
    'Sri Lanka Rupee': 'LKR',
    'Moroccan Dirham': 'MAD',
    'Macedonia Denar': 'MKD',
    'Mexican Peso': 'MXN',
    'Malaysia Ringgit': 'MYR',
    'Nigerian Naira': 'NGN',
    'Omani Rial': 'OMR',
    'Peru Sol': 'PEN',
    'Pakistan Rupee': 'PKR',
    'Philippine Piso': 'PHP',
    'Polish Zloty': 'PLN',
    'Qatari Riyal': 'QAR',
    'Serbian Dinar': 'RSD',
    'Russian Rouble': 'RUB',
     'Trin Tob Dollar':'TTD',
     'Russia Rouble':'RUB',
    'Sudanese Pound': 'SDG',
    'Thai Baht': 'THB',
    'Tunisian Dinar': 'TND',
    'Turkish Lira': 'TRY',
    'Trinidad and Tobago Dollar': 'TTD',
    'Tanzania Shilling': 'TZS',
    'Uganda Shilling': 'UGX',
    'Vietnam Dong': 'VND',
    'Yemen Rial': 'YER',
    'Zambian Kwacha': 'ZMW',
    'South Africa Rand': 'ZAR',
    'Azerbaijan Manat': 'AZN',
    'Azerbaijan manat':'AZN',
    'Bulgarian Lev': 'BGN',
    'Iraqi Dinar': 'IQD',
    'Israeli New Shekel': 'ILS',
    'Libyan Dinar': 'LYD',
    'Mauritian Rupee': 'MUR',
    'Romanian Leu': 'RON',
    'Syrian Pound': 'SYP',
    'Turkmen Manat': 'TMT',
    'Uzbekistani Som': 'UZS',
    'Iranian Rial': 'IRR',
    'Australian Dollor': 'AUD',
    'Australian Dollar': 'AUD',
    'Swiss Franc': 'CHF',
    'Singapore Dollar': 'SGD',
    'Phillipines Peso': 'PHP',
    'US Dollar': 'USD',
    'Euro': 'EUR',
    'UK Pound': 'GBP',
    'GB Pound':'GBP',
    'Canadian Dollar': 'CAD',
    'New Zealand DOLLAR': 'NZD',
    'NewZealand Dollar': 'NZD',
    'Japanese Yen': 'JPY',
    'Swedish Krona': 'SEK',
    'Norwegian Krone': 'NOK',
    'Danish Krone': 'DKK',
    'Labenese Pound': 'LBP',
    'Egypt Pound': 'EGP',
    'Turkey Lira': 'TRY',
    'Jordan Dinar': 'JOD',
    'Saudi Riyal': 'SAR',
    'Bahrani Dinar':'BHD',
    'Bahrain Dinar': 'BHD',
    'Oman Rial': 'OMR',
    'Yemen Riyal': 'YER',
    'Scotland Pound': 'SCO',  # Not official, using 'SCO' as placeholder
    'S. Africa': 'ZAR',
    'Tunis Dinar': 'TND',
    'Ethiopian Birr': 'ETB',
    'Kuwait Dinar': 'KWD',
    'Algerian Dinar': 'DZD',
    'Morocco Dirham': 'MAD',
    'Indonesia Rupiah': 'IDR',
    'Indonesian Rupiah': 'IDR',
    'Mauritius Rupee': 'MUR',
    'Thailand Bhat': 'THB',
    'Taiwan Dollar': 'TWD',
    'Brunei Dollar': 'BND',
    'Malaysian Ringgit': 'MYR',
    'Indian Ruppee': 'INR',
    'Indian Rupee':'INR',
}

currency_name_to_code = {
    'argentine peso': 'ARS',
    'bangladesh taka': 'BDT',
    'bahraini dinar': 'BHD',
    'hongkong dollar': 'HKD',
    'brazilian real': 'BRL',
    'botswana pula': 'BWP',
    'belarus rouble': 'BYN',
    'chilean peso': 'CLP',
    'chinese yuan - offshore': 'CNH',
    'chinese yuan': 'CNY',
    'colombian peso': 'COP',
    'czech koruna': 'CZK',
    'hong kong dollar': 'HKD',
    'hungarian forint': 'HUF',
    'iceland krona': 'ISK',
    'kenya shilling': 'KES',
    'korean won': 'KRW',
    'kuwaiti dinar': 'KWD',
    'kazakhstan tenge': 'KZT',
    'lebanon pound': 'LBP',
    'sri lanka rupee': 'LKR',
    'moroccan dirham': 'MAD',
    'macedonia denar': 'MKD',
    'mexican peso': 'MXN',
    'malaysia ringgit': 'MYR',
    'nigerian naira': 'NGN',
    'omani rial': 'OMR',
    'peru sol': 'PEN',
    'pakistan rupee': 'PKR',
    'philippine piso': 'PHP',
    'polish zloty': 'PLN',
    'qatari riyal': 'QAR',
    'serbian dinar': 'RSD',
    'russian rouble': 'RUB',
    'trin tob dollar': 'TTD',
    'russia rouble': 'RUB',
    'sudanese pound': 'SDG',
    'thai baht': 'THB',
    'tunisian dinar': 'TND',
    'turkish lira': 'TRY',
    'trinidad and tobago dollar': 'TTD',
    'tanzania shilling': 'TZS',
    'uganda shilling': 'UGX',
    'vietnam dong': 'VND',
    'yemen rial': 'YER',
    'zambian kwacha': 'ZMW',
    'south africa rand': 'ZAR',
    'azerbaijan manat': 'AZN',
    'azerbaijan manat': 'AZN',
    'bulgarian lev': 'BGN',
    'iraqi dinar': 'IQD',
    'israeli new shekel': 'ILS',
    'libyan dinar': 'LYD',
    'mauritian rupee': 'MUR',
    'romanian leu': 'RON',
    'syrian pound': 'SYP',
    'turkmen manat': 'TMT',
    'uzbekistani som': 'UZS',
    'iranian rial': 'IRR',
    'australian dollor': 'AUD',
    'australian dollar': 'AUD',
    'swiss franc': 'CHF',
    'singapore dollar': 'SGD',
    'phillipines peso': 'PHP',
    'us dollar': 'USD',
    'euro': 'EUR',
    'uk pound': 'GBP',
    'gb pound': 'GBP',
    'canadian dollar': 'CAD',
    'new zealand dollar': 'NZD',
    'newzealand dollar': 'NZD',
    'japanese yen': 'JPY',
    'swedish krona': 'SEK',
    'norwegian krone': 'NOK',
    'danish krone': 'DKK',
    'labenese pound': 'LBP',
    'egypt pound': 'EGP',
    'turkey lira': 'TRY',
    'jordan dinar': 'JOD',
    'saudi riyal': 'SAR',
    'bahrani dinar': 'BHD',
    'bahrain dinar': 'BHD',
    'oman rial': 'OMR',
    'yemen riyal': 'YER',
    'scotland pound': 'SCO',
    's. africa': 'ZAR',
    'tunis dinar': 'TND',
    'ethiopian birr': 'ETB',
    'kuwait dinar': 'KWD',
    'algerian dinar': 'DZD',
    'morocco dirham': 'MAD',
    'indonesia rupiah': 'IDR',
    'indonesian rupiah': 'IDR',
    'mauritius rupee': 'MUR',
    'thailand bhat': 'THB',
    'taiwan dollar': 'TWD',
    'brunei dollar': 'BND',
    'malaysian ringgit': 'MYR',
    'indian ruppee': 'INR',
    'indian rupee': 'INR',
}


